using LegioSoft.Imaging.Skia.SVG.Models;
using SkiaSharp;

namespace LegioSoft.Imaging.Skia.SVG.Interfaces;

public interface ISvgElementVisitor
{
    void Visit(SvgRect element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgCircle element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgEllipse element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgLine element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgPolyline element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgPolygon element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgPath element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgGroup element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgDefs element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgDesc element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgTitle element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgSymbol element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgUse element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgImage element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgSwitch element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgStyleElement element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgForeignObject element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgText element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgTSpan element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgTextPath element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAnchor element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAltGlyph element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAltGlyphDef element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAltGlyphItem element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgGlyphRef element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgMarker element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgMask element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgClipPath element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgLinearGradient element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgRadialGradient element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgPattern element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFilter element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeBlend element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeColorMatrix element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeComponentTransfer element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeFuncR element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeFuncG element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeFuncB element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeFuncA element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeComposite element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeConvolveMatrix element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeDiffuseLighting element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeDisplacementMap element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeDistantLight element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeFlood element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeGaussianBlur element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeImage element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeMerge element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeMergeNode element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeMorphology element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeOffset element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFePointLight element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeSpecularLighting element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeSpotLight element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeTile element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeTurbulence element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFeDropShadow element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAnimate element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAnimateMotion element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgAnimateTransform element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgMPath element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgSet element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgView element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgScript element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgMetadata element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgCursor element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgSolidColor element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFont element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFontFace element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgGlyph element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgMissingGlyph element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgHKern element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgVKern element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFontFaceSrc element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFontFaceUri element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFontFaceFormat element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgFontFaceName element, SKCanvas canvas, SKMatrix transform);
    void Visit(SvgColorProfile element, SKCanvas canvas, SKMatrix transform);
}
